defmodule StellarBase.XDR.BeginSponsoringFutureReservesOp do
  @moduledoc """
  Automatically generated by xdrgen
  DO NOT EDIT or your changes may be overwritten

  Target implementation: elixir_xdr at https://hex.pm/packages/elixir_xdr

  Representation of Stellar `BeginSponsoringFutureReservesOp` type.
  """

  @behaviour XDR.Declaration

  alias StellarBase.XDR.AccountID

  @struct_spec XDR.Struct.new(sponsored_id: AccountID)

  @type sponsored_id_type :: AccountID.t()

  @type t :: %__MODULE__{sponsored_id: sponsored_id_type()}

  defstruct [:sponsored_id]

  @spec new(sponsored_id :: sponsored_id_type()) :: t()
  def new(%AccountID{} = sponsored_id),
    do: %__MODULE__{sponsored_id: sponsored_id}

  @impl true
  def encode_xdr(%__MODULE__{sponsored_id: sponsored_id}) do
    [sponsored_id: sponsored_id]
    |> XDR.Struct.new()
    |> XDR.Struct.encode_xdr()
  end

  @impl true
  def encode_xdr!(%__MODULE__{sponsored_id: sponsored_id}) do
    [sponsored_id: sponsored_id]
    |> XDR.Struct.new()
    |> XDR.Struct.encode_xdr!()
  end

  @impl true
  def decode_xdr(bytes, struct \\ @struct_spec)

  def decode_xdr(bytes, struct) do
    case XDR.Struct.decode_xdr(bytes, struct) do
      {:ok, {%XDR.Struct{components: [sponsored_id: sponsored_id]}, rest}} ->
        {:ok, {new(sponsored_id), rest}}

      error ->
        error
    end
  end

  @impl true
  def decode_xdr!(bytes, struct \\ @struct_spec)

  def decode_xdr!(bytes, struct) do
    {%XDR.Struct{components: [sponsored_id: sponsored_id]}, rest} =
      XDR.Struct.decode_xdr!(bytes, struct)

    {new(sponsored_id), rest}
  end
end
