defmodule StellarBase.XDR.BucketMetadata do
  @moduledoc """
  Automatically generated by xdrgen
  DO NOT EDIT or your changes may be overwritten

  Target implementation: elixir_xdr at https://hex.pm/packages/elixir_xdr

  Representation of Stellar `BucketMetadata` type.
  """

  @behaviour XDR.Declaration

  alias StellarBase.XDR.{
    Uint32,
    BucketMetadataExt
  }

  @struct_spec XDR.Struct.new(
                 ledger_version: Uint32,
                 ext: BucketMetadataExt
               )

  @type ledger_version_type :: Uint32.t()
  @type ext_type :: BucketMetadataExt.t()

  @type t :: %__MODULE__{ledger_version: ledger_version_type(), ext: ext_type()}

  defstruct [:ledger_version, :ext]

  @spec new(ledger_version :: ledger_version_type(), ext :: ext_type()) :: t()
  def new(
        %Uint32{} = ledger_version,
        %BucketMetadataExt{} = ext
      ),
      do: %__MODULE__{ledger_version: ledger_version, ext: ext}

  @impl true
  def encode_xdr(%__MODULE__{ledger_version: ledger_version, ext: ext}) do
    [ledger_version: ledger_version, ext: ext]
    |> XDR.Struct.new()
    |> XDR.Struct.encode_xdr()
  end

  @impl true
  def encode_xdr!(%__MODULE__{ledger_version: ledger_version, ext: ext}) do
    [ledger_version: ledger_version, ext: ext]
    |> XDR.Struct.new()
    |> XDR.Struct.encode_xdr!()
  end

  @impl true
  def decode_xdr(bytes, struct \\ @struct_spec)

  def decode_xdr(bytes, struct) do
    case XDR.Struct.decode_xdr(bytes, struct) do
      {:ok, {%XDR.Struct{components: [ledger_version: ledger_version, ext: ext]}, rest}} ->
        {:ok, {new(ledger_version, ext), rest}}

      error ->
        error
    end
  end

  @impl true
  def decode_xdr!(bytes, struct \\ @struct_spec)

  def decode_xdr!(bytes, struct) do
    {%XDR.Struct{components: [ledger_version: ledger_version, ext: ext]}, rest} =
      XDR.Struct.decode_xdr!(bytes, struct)

    {new(ledger_version, ext), rest}
  end
end
