defmodule StellarBase.XDR.ClaimOfferAtom do
  @moduledoc """
  Automatically generated by xdrgen
  DO NOT EDIT or your changes may be overwritten

  Target implementation: elixir_xdr at https://hex.pm/packages/elixir_xdr

  Representation of Stellar `ClaimOfferAtom` type.
  """

  @behaviour XDR.Declaration

  alias StellarBase.XDR.{
    AccountID,
    Int64,
    Asset
  }

  @struct_spec XDR.Struct.new(
    seller_id: AccountID,
    offer_id: Int64,
    asset_sold: Asset,
    amount_sold: Int64,
    asset_bought: Asset,
    amount_bought: Int64
  )

  @type type_seller_id :: AccountID.t()
  @type type_offer_id :: Int64.t()
  @type type_asset_sold :: Asset.t()
  @type type_amount_sold :: Int64.t()
  @type type_asset_bought :: Asset.t()
  @type type_amount_bought :: Int64.t()

  @type t :: %__MODULE__{seller_id: type_seller_id(), offer_id: type_offer_id(), asset_sold: type_asset_sold(), amount_sold: type_amount_sold(), asset_bought: type_asset_bought(), amount_bought: type_amount_bought()}

  defstruct [:seller_id, :offer_id, :asset_sold, :amount_sold, :asset_bought, :amount_bought]

  @spec new(seller_id :: type_seller_id(), offer_id :: type_offer_id(), asset_sold :: type_asset_sold(), amount_sold :: type_amount_sold(), asset_bought :: type_asset_bought(), amount_bought :: type_amount_bought()) :: t()
  def new(
    %AccountID{} = seller_id,
    %Int64{} = offer_id,
    %Asset{} = asset_sold,
    %Int64{} = amount_sold,
    %Asset{} = asset_bought,
    %Int64{} = amount_bought
  ),
  do: %__MODULE__{seller_id: seller_id, offer_id: offer_id, asset_sold: asset_sold, amount_sold: amount_sold, asset_bought: asset_bought, amount_bought: amount_bought}

  @impl true
  def encode_xdr(%__MODULE__{seller_id: seller_id, offer_id: offer_id, asset_sold: asset_sold, amount_sold: amount_sold, asset_bought: asset_bought, amount_bought: amount_bought}) do
    [seller_id: seller_id, offer_id: offer_id, asset_sold: asset_sold, amount_sold: amount_sold, asset_bought: asset_bought, amount_bought: amount_bought]
    |> XDR.Struct.new()
    |> XDR.Struct.encode_xdr()
  end

  @impl true
  def encode_xdr!(%__MODULE__{seller_id: seller_id, offer_id: offer_id, asset_sold: asset_sold, amount_sold: amount_sold, asset_bought: asset_bought, amount_bought: amount_bought}) do
    [seller_id: seller_id, offer_id: offer_id, asset_sold: asset_sold, amount_sold: amount_sold, asset_bought: asset_bought, amount_bought: amount_bought]
    |> XDR.Struct.new()
    |> XDR.Struct.encode_xdr!()
  end

  @impl true
  def decode_xdr(bytes, struct \\ @struct_spec)

  def decode_xdr(bytes, struct) do
    case XDR.Struct.decode_xdr(bytes, struct) do
      {:ok, {%XDR.Struct{components: [seller_id: seller_id, offer_id: offer_id, asset_sold: asset_sold, amount_sold: amount_sold, asset_bought: asset_bought, amount_bought: amount_bought]}, rest}} ->
        {:ok, {new(seller_id, offer_id, asset_sold, amount_sold, asset_bought, amount_bought), rest}}
      error -> error
    end
  end

  @impl true
  def decode_xdr!(bytes, struct \\ @struct_spec)

  def decode_xdr!(bytes, struct) do
    {%XDR.Struct{components: [seller_id: seller_id, offer_id: offer_id, asset_sold: asset_sold, amount_sold: amount_sold, asset_bought: asset_bought, amount_bought: amount_bought]}, rest} =
      XDR.Struct.decode_xdr!(bytes, struct)
    {new(seller_id, offer_id, asset_sold, amount_sold, asset_bought, amount_bought), rest}
  end
end
