defmodule StellarBase.XDR.ClawbackOp do
  @moduledoc """
  Automatically generated by xdrgen
  DO NOT EDIT or your changes may be overwritten

  Target implementation: elixir_xdr at https://hex.pm/packages/elixir_xdr

  Representation of Stellar `ClawbackOp` type.
  """

  @behaviour XDR.Declaration

  alias StellarBase.XDR.{
    Asset,
    MuxedAccount,
    Int64
  }

  @struct_spec XDR.Struct.new(
    asset: Asset,
    from: MuxedAccount,
    amount: Int64
  )

  @type type_asset :: Asset.t()
  @type type_from :: MuxedAccount.t()
  @type type_amount :: Int64.t()

  @type t :: %__MODULE__{asset: type_asset(), from: type_from(), amount: type_amount()}

  defstruct [:asset, :from, :amount]

  @spec new(asset :: type_asset(), from :: type_from(), amount :: type_amount()) :: t()
  def new(
    %Asset{} = asset,
    %MuxedAccount{} = from,
    %Int64{} = amount
  ),
  do: %__MODULE__{asset: asset, from: from, amount: amount}

  @impl true
  def encode_xdr(%__MODULE__{asset: asset, from: from, amount: amount}) do
    [asset: asset, from: from, amount: amount]
    |> XDR.Struct.new()
    |> XDR.Struct.encode_xdr()
  end

  @impl true
  def encode_xdr!(%__MODULE__{asset: asset, from: from, amount: amount}) do
    [asset: asset, from: from, amount: amount]
    |> XDR.Struct.new()
    |> XDR.Struct.encode_xdr!()
  end

  @impl true
  def decode_xdr(bytes, struct \\ @struct_spec)

  def decode_xdr(bytes, struct) do
    case XDR.Struct.decode_xdr(bytes, struct) do
      {:ok, {%XDR.Struct{components: [asset: asset, from: from, amount: amount]}, rest}} ->
        {:ok, {new(asset, from, amount), rest}}
      error -> error
    end
  end

  @impl true
  def decode_xdr!(bytes, struct \\ @struct_spec)

  def decode_xdr!(bytes, struct) do
    {%XDR.Struct{components: [asset: asset, from: from, amount: amount]}, rest} =
      XDR.Struct.decode_xdr!(bytes, struct)
    {new(asset, from, amount), rest}
  end
end
