defmodule StellarBase.XDR.EncryptedBody do
  @moduledoc """
  Automatically generated by xdrgen
  DO NOT EDIT or your changes may be overwritten

  Target implementation: elixir_xdr at https://hex.pm/packages/elixir_xdr

  Representation of Stellar `EncryptedBody` type.
  """

  @behaviour XDR.Declaration

  alias StellarBase.XDR.VariableOpaque64000

  @type t :: %__MODULE__{value: binary()}

  defstruct [:value]

  @spec new(value :: binary()) :: t()
  def new(value), do: %__MODULE__{value: value}

  @impl true
  def encode_xdr(%__MODULE__{value: value}) do
    value
    |> VariableOpaque64000.new()
    |> VariableOpaque64000.encode_xdr()
  end

  @impl true
  def encode_xdr!(%__MODULE__{value: value}) do
    value
    |> VariableOpaque64000.new()
    |> VariableOpaque64000.encode_xdr!()
  end

  @impl true
  def decode_xdr(bytes, term \\ nil)

  def decode_xdr(bytes, _term) do
    case VariableOpaque64000.decode_xdr(bytes) do
      {:ok, {%VariableOpaque64000{opaque: value}, rest}} -> {:ok, {new(value), rest}}
      error -> error
    end
  end

  @impl true
  def decode_xdr!(bytes, term \\ nil)

  def decode_xdr!(bytes, _term) do
    {%VariableOpaque64000{opaque: value}, rest} = VariableOpaque64000.decode_xdr!(bytes)
    {new(value), rest}
  end
end
