defmodule StellarBase.XDR.InflationPayout do
  @moduledoc """
  Automatically generated by xdrgen
  DO NOT EDIT or your changes may be overwritten

  Target implementation: elixir_xdr at https://hex.pm/packages/elixir_xdr

  Representation of Stellar `InflationPayout` type.
  """

  @behaviour XDR.Declaration

  alias StellarBase.XDR.{
    AccountID,
    Int64
  }

  @struct_spec XDR.Struct.new(
                 destination: AccountID,
                 amount: Int64
               )

  @type destination_type :: AccountID.t()
  @type amount_type :: Int64.t()

  @type t :: %__MODULE__{destination: destination_type(), amount: amount_type()}

  defstruct [:destination, :amount]

  @spec new(destination :: destination_type(), amount :: amount_type()) :: t()
  def new(
        %AccountID{} = destination,
        %Int64{} = amount
      ),
      do: %__MODULE__{destination: destination, amount: amount}

  @impl true
  def encode_xdr(%__MODULE__{destination: destination, amount: amount}) do
    [destination: destination, amount: amount]
    |> XDR.Struct.new()
    |> XDR.Struct.encode_xdr()
  end

  @impl true
  def encode_xdr!(%__MODULE__{destination: destination, amount: amount}) do
    [destination: destination, amount: amount]
    |> XDR.Struct.new()
    |> XDR.Struct.encode_xdr!()
  end

  @impl true
  def decode_xdr(bytes, struct \\ @struct_spec)

  def decode_xdr(bytes, struct) do
    case XDR.Struct.decode_xdr(bytes, struct) do
      {:ok, {%XDR.Struct{components: [destination: destination, amount: amount]}, rest}} ->
        {:ok, {new(destination, amount), rest}}

      error ->
        error
    end
  end

  @impl true
  def decode_xdr!(bytes, struct \\ @struct_spec)

  def decode_xdr!(bytes, struct) do
    {%XDR.Struct{components: [destination: destination, amount: amount]}, rest} =
      XDR.Struct.decode_xdr!(bytes, struct)

    {new(destination, amount), rest}
  end
end
