defmodule StellarBase.XDR.LedgerSCPMessages do
  @moduledoc """
  Automatically generated by xdrgen
  DO NOT EDIT or your changes may be overwritten

  Target implementation: elixir_xdr at https://hex.pm/packages/elixir_xdr

  Representation of Stellar `LedgerSCPMessages` type.
  """

  @behaviour XDR.Declaration

  alias StellarBase.XDR.{
    Uint32,
    SCPEnvelopeList
  }

  @struct_spec XDR.Struct.new(
    ledger_seq: Uint32,
    messages: SCPEnvelopeList
  )

  @type type_ledger_seq :: Uint32.t()
  @type type_messages :: SCPEnvelopeList.t()

  @type t :: %__MODULE__{ledger_seq: type_ledger_seq(), messages: type_messages()}

  defstruct [:ledger_seq, :messages]

  @spec new(ledger_seq :: type_ledger_seq(), messages :: type_messages()) :: t()
  def new(
    %Uint32{} = ledger_seq,
    %SCPEnvelopeList{} = messages
  ),
  do: %__MODULE__{ledger_seq: ledger_seq, messages: messages}

  @impl true
  def encode_xdr(%__MODULE__{ledger_seq: ledger_seq, messages: messages}) do
    [ledger_seq: ledger_seq, messages: messages]
    |> XDR.Struct.new()
    |> XDR.Struct.encode_xdr()
  end

  @impl true
  def encode_xdr!(%__MODULE__{ledger_seq: ledger_seq, messages: messages}) do
    [ledger_seq: ledger_seq, messages: messages]
    |> XDR.Struct.new()
    |> XDR.Struct.encode_xdr!()
  end

  @impl true
  def decode_xdr(bytes, struct \\ @struct_spec)

  def decode_xdr(bytes, struct) do
    case XDR.Struct.decode_xdr(bytes, struct) do
      {:ok, {%XDR.Struct{components: [ledger_seq: ledger_seq, messages: messages]}, rest}} ->
        {:ok, {new(ledger_seq, messages), rest}}
      error -> error
    end
  end

  @impl true
  def decode_xdr!(bytes, struct \\ @struct_spec)

  def decode_xdr!(bytes, struct) do
    {%XDR.Struct{components: [ledger_seq: ledger_seq, messages: messages]}, rest} =
      XDR.Struct.decode_xdr!(bytes, struct)
    {new(ledger_seq, messages), rest}
  end
end
