defmodule StellarBase.XDR.LedgerHeaderFlags do
  @moduledoc """
  Automatically generated by xdrgen
  DO NOT EDIT or your changes may be overwritten

  Target implementation: elixir_xdr at https://hex.pm/packages/elixir_xdr

  Representation of Stellar `LedgerHeaderFlags` type.
  """

  @behaviour XDR.Declaration

  @declarations [
    DISABLE_LIQUIDITY_POOL_TRADING_FLAG: 1,
    DISABLE_LIQUIDITY_POOL_DEPOSIT_FLAG: 2,
    DISABLE_LIQUIDITY_POOL_WITHDRAWAL_FLAG: 4,
    DISABLE_CONTRACT_CREATE: 8,
    DISABLE_CONTRACT_UPDATE: 16,
    DISABLE_CONTRACT_REMOVE: 32,
    DISABLE_CONTRACT_INVOKE: 64
  ]

  @enum_spec %XDR.Enum{declarations: @declarations, identifier: nil}

  @type t :: %__MODULE__{identifier: atom()}

  defstruct [:identifier]

  @spec new(type :: atom()) :: t()
  def new(type \\ :DISABLE_LIQUIDITY_POOL_TRADING_FLAG), do: %__MODULE__{identifier: type}

  @impl true
  def encode_xdr(%__MODULE__{identifier: type}) do
    @declarations
    |> XDR.Enum.new(type)
    |> XDR.Enum.encode_xdr()
  end

  @impl true
  def encode_xdr!(%__MODULE__{identifier: type}) do
    @declarations
    |> XDR.Enum.new(type)
    |> XDR.Enum.encode_xdr!()
  end

  @impl true
  def decode_xdr(bytes, spec \\ @enum_spec)

  def decode_xdr(bytes, spec) do
    case XDR.Enum.decode_xdr(bytes, spec) do
      {:ok, {%XDR.Enum{identifier: type}, rest}} -> {:ok, {new(type), rest}}
      error -> error
    end
  end

  @impl true
  def decode_xdr!(bytes, spec \\ @enum_spec)

  def decode_xdr!(bytes, spec) do
    {%XDR.Enum{identifier: type}, rest} = XDR.Enum.decode_xdr!(bytes, spec)
    {new(type), rest}
  end
end
