defmodule StellarBase.XDR.LedgerEntryExtensionV1 do
  @moduledoc """
  Automatically generated by xdrgen
  DO NOT EDIT or your changes may be overwritten

  Target implementation: elixir_xdr at https://hex.pm/packages/elixir_xdr

  Representation of Stellar `LedgerEntryExtensionV1` type.
  """

  @behaviour XDR.Declaration

  alias StellarBase.XDR.{
    SponsorshipDescriptor,
    LedgerEntryExtensionV1Ext
  }

  @struct_spec XDR.Struct.new(
    sponsoring_id: SponsorshipDescriptor,
    ext: LedgerEntryExtensionV1Ext
  )

  @type type_sponsoring_id :: SponsorshipDescriptor.t()
  @type type_ext :: LedgerEntryExtensionV1Ext.t()

  @type t :: %__MODULE__{sponsoring_id: type_sponsoring_id(), ext: type_ext()}

  defstruct [:sponsoring_id, :ext]

  @spec new(sponsoring_id :: type_sponsoring_id(), ext :: type_ext()) :: t()
  def new(
    %SponsorshipDescriptor{} = sponsoring_id,
    %LedgerEntryExtensionV1Ext{} = ext
  ),
  do: %__MODULE__{sponsoring_id: sponsoring_id, ext: ext}

  @impl true
  def encode_xdr(%__MODULE__{sponsoring_id: sponsoring_id, ext: ext}) do
    [sponsoring_id: sponsoring_id, ext: ext]
    |> XDR.Struct.new()
    |> XDR.Struct.encode_xdr()
  end

  @impl true
  def encode_xdr!(%__MODULE__{sponsoring_id: sponsoring_id, ext: ext}) do
    [sponsoring_id: sponsoring_id, ext: ext]
    |> XDR.Struct.new()
    |> XDR.Struct.encode_xdr!()
  end

  @impl true
  def decode_xdr(bytes, struct \\ @struct_spec)

  def decode_xdr(bytes, struct) do
    case XDR.Struct.decode_xdr(bytes, struct) do
      {:ok, {%XDR.Struct{components: [sponsoring_id: sponsoring_id, ext: ext]}, rest}} ->
        {:ok, {new(sponsoring_id, ext), rest}}
      error -> error
    end
  end

  @impl true
  def decode_xdr!(bytes, struct \\ @struct_spec)

  def decode_xdr!(bytes, struct) do
    {%XDR.Struct{components: [sponsoring_id: sponsoring_id, ext: ext]}, rest} =
      XDR.Struct.decode_xdr!(bytes, struct)
    {new(sponsoring_id, ext), rest}
  end
end
