defmodule StellarBase.XDR.MessageType do
  @moduledoc """
  Automatically generated by xdrgen
  DO NOT EDIT or your changes may be overwritten

  Target implementation: elixir_xdr at https://hex.pm/packages/elixir_xdr

  Representation of Stellar `MessageType` type.
  """

  @behaviour XDR.Declaration

  @declarations [
    ERROR_MSG: 0,
    AUTH: 2,
    DONT_HAVE: 3,
    GET_PEERS: 4,
    PEERS: 5,
    GET_TX_SET: 6,
    TX_SET: 7,
    GENERALIZED_TX_SET: 17,
    TRANSACTION: 8,
    GET_SCP_QUORUMSET: 9,
    SCP_QUORUMSET: 10,
    SCP_MESSAGE: 11,
    GET_SCP_STATE: 12,
    HELLO: 13,
    SURVEY_REQUEST: 14,
    SURVEY_RESPONSE: 15,
    SEND_MORE: 16,
    FLOOD_ADVERT: 18,
    FLOOD_DEMAND: 19
  ]

  @enum_spec %XDR.Enum{declarations: @declarations, identifier: nil}

  @type t :: %__MODULE__{identifier: atom()}

  defstruct [:identifier]

  @spec new(type :: atom()) :: t()
  def new(type \\ :ERROR_MSG), do: %__MODULE__{identifier: type}

  @impl true
  def encode_xdr(%__MODULE__{identifier: type}) do
    @declarations
    |> XDR.Enum.new(type)
    |> XDR.Enum.encode_xdr()
  end

  @impl true
  def encode_xdr!(%__MODULE__{identifier: type}) do
    @declarations
    |> XDR.Enum.new(type)
    |> XDR.Enum.encode_xdr!()
  end

  @impl true
  def decode_xdr(bytes, spec \\ @enum_spec)

  def decode_xdr(bytes, spec) do
    case XDR.Enum.decode_xdr(bytes, spec) do
      {:ok, {%XDR.Enum{identifier: type}, rest}} -> {:ok, {new(type), rest}}
      error -> error
    end
  end

  @impl true
  def decode_xdr!(bytes, spec \\ @enum_spec)

  def decode_xdr!(bytes, spec) do
    {%XDR.Enum{identifier: type}, rest} = XDR.Enum.decode_xdr!(bytes, spec)
    {new(type), rest}
  end
end
