defmodule StellarBase.XDR.OptionalDataValue do
  @moduledoc """
  Automatically generated by xdrgen
  DO NOT EDIT or your changes may be overwritten

  Target implementation: elixir_xdr at https://hex.pm/packages/elixir_xdr

  Representation of Stellar `OptionalDataValue` type.
  """

  @behaviour XDR.Declaration

  alias StellarBase.XDR.DataValue

  @optional_spec XDR.Optional.new(DataValue)

  @type data_value :: DataValue.t() | nil

  @type t :: %__MODULE__{data_value: data_value()}

  defstruct [:data_value]

  @spec new(data_value :: data_value()) :: t()
  def new(data_value \\ nil), do: %__MODULE__{data_value: data_value}

  @impl true
  def encode_xdr(%__MODULE__{data_value: data_value}) do
    data_value
    |> XDR.Optional.new()
    |> XDR.Optional.encode_xdr()
  end

  @impl true
  def encode_xdr!(%__MODULE__{data_value: data_value}) do
    data_value
    |> XDR.Optional.new()
    |> XDR.Optional.encode_xdr!()
  end

  @impl true
  def decode_xdr(bytes, optional_spec \\ @optional_spec)

  def decode_xdr(bytes, optional_spec) do
    case XDR.Optional.decode_xdr(bytes, optional_spec) do
      {:ok, {%XDR.Optional{type: data_value}, rest}} -> {:ok, {new(data_value), rest}}
      {:ok, {nil, rest}} -> {:ok, {new(), rest}}
      error -> error
    end
  end

  @impl true
  def decode_xdr!(bytes, optional_spec \\ @optional_spec)

  def decode_xdr!(bytes, optional_spec) do
    case XDR.Optional.decode_xdr!(bytes, optional_spec) do
      {%XDR.Optional{type: data_value}, rest} -> {new(data_value), rest}
      {nil, rest} -> {new(), rest}
    end
  end

end
