defmodule StellarBase.XDR.OptionalClaimPredicate do
  @moduledoc """
  Automatically generated by xdrgen
  DO NOT EDIT or your changes may be overwritten

  Target implementation: elixir_xdr at https://hex.pm/packages/elixir_xdr

  Representation of Stellar `OptionalClaimPredicate` type.
  """

  @behaviour XDR.Declaration

  alias StellarBase.XDR.ClaimPredicate

  @optional_spec XDR.Optional.new(ClaimPredicate)

  @type claim_predicate :: ClaimPredicate.t() | nil

  @type t :: %__MODULE__{claim_predicate: claim_predicate()}

  defstruct [:claim_predicate]

  @spec new(claim_predicate :: claim_predicate()) :: t()
  def new(claim_predicate \\ nil), do: %__MODULE__{claim_predicate: claim_predicate}

  @impl true
  def encode_xdr(%__MODULE__{claim_predicate: claim_predicate}) do
    claim_predicate
    |> XDR.Optional.new()
    |> XDR.Optional.encode_xdr()
  end

  @impl true
  def encode_xdr!(%__MODULE__{claim_predicate: claim_predicate}) do
    claim_predicate
    |> XDR.Optional.new()
    |> XDR.Optional.encode_xdr!()
  end

  @impl true
  def decode_xdr(bytes, optional_spec \\ @optional_spec)

  def decode_xdr(bytes, optional_spec) do
    case XDR.Optional.decode_xdr(bytes, optional_spec) do
      {:ok, {%XDR.Optional{type: claim_predicate}, rest}} -> {:ok, {new(claim_predicate), rest}}
      {:ok, {nil, rest}} -> {:ok, {new(), rest}}
      error -> error
    end
  end

  @impl true
  def decode_xdr!(bytes, optional_spec \\ @optional_spec)

  def decode_xdr!(bytes, optional_spec) do
    case XDR.Optional.decode_xdr!(bytes, optional_spec) do
      {%XDR.Optional{type: claim_predicate}, rest} -> {new(claim_predicate), rest}
      {nil, rest} -> {new(), rest}
    end
  end
end
