defmodule StellarBase.XDR.OptionalMuxedAccount do
  @moduledoc """
  Automatically generated by xdrgen
  DO NOT EDIT or your changes may be overwritten

  Target implementation: elixir_xdr at https://hex.pm/packages/elixir_xdr

  Representation of Stellar `OptionalMuxedAccount` type.
  """

  @behaviour XDR.Declaration

  alias StellarBase.XDR.MuxedAccount

  @optional_spec XDR.Optional.new(MuxedAccount)

  @type muxed_account :: MuxedAccount.t() | nil

  @type t :: %__MODULE__{muxed_account: muxed_account()}

  defstruct [:muxed_account]

  @spec new(muxed_account :: muxed_account()) :: t()
  def new(muxed_account \\ nil), do: %__MODULE__{muxed_account: muxed_account}

  @impl true
  def encode_xdr(%__MODULE__{muxed_account: muxed_account}) do
    muxed_account
    |> XDR.Optional.new()
    |> XDR.Optional.encode_xdr()
  end

  @impl true
  def encode_xdr!(%__MODULE__{muxed_account: muxed_account}) do
    muxed_account
    |> XDR.Optional.new()
    |> XDR.Optional.encode_xdr!()
  end

  @impl true
  def decode_xdr(bytes, optional_spec \\ @optional_spec)

  def decode_xdr(bytes, optional_spec) do
    case XDR.Optional.decode_xdr(bytes, optional_spec) do
      {:ok, {%XDR.Optional{type: muxed_account}, rest}} -> {:ok, {new(muxed_account), rest}}
      {:ok, {nil, rest}} -> {:ok, {new(), rest}}
      error -> error
    end
  end

  @impl true
  def decode_xdr!(bytes, optional_spec \\ @optional_spec)

  def decode_xdr!(bytes, optional_spec) do
    case XDR.Optional.decode_xdr!(bytes, optional_spec) do
      {%XDR.Optional{type: muxed_account}, rest} -> {new(muxed_account), rest}
      {nil, rest} -> {new(), rest}
    end
  end

end
