defmodule StellarBase.XDR.SCSpecFunctionV0 do
  @moduledoc """
  Automatically generated by xdrgen
  DO NOT EDIT or your changes may be overwritten

  Target implementation: elixir_xdr at https://hex.pm/packages/elixir_xdr

  Representation of Stellar `SCSpecFunctionV0` type.
  """

  @behaviour XDR.Declaration

  alias StellarBase.XDR.{
    String1024,
    SCSymbol,
    SCSpecFunctionInputV0List10,
    SCSpecTypeDefList1
  }

  @struct_spec XDR.Struct.new(
    doc: String1024,
    name: SCSymbol,
    inputs: SCSpecFunctionInputV0List10,
    outputs: SCSpecTypeDefList1
  )

  @type doc_type :: String1024.t()
  @type name_type :: SCSymbol.t()
  @type inputs_type :: SCSpecFunctionInputV0List10.t()
  @type outputs_type :: SCSpecTypeDefList1.t()

  @type t :: %__MODULE__{doc: doc_type(), name: name_type(), inputs: inputs_type(), outputs: outputs_type()}

  defstruct [:doc, :name, :inputs, :outputs]

  @spec new(doc :: doc_type(), name :: name_type(), inputs :: inputs_type(), outputs :: outputs_type()) :: t()
  def new(
    %String1024{} = doc,
    %SCSymbol{} = name,
    %SCSpecFunctionInputV0List10{} = inputs,
    %SCSpecTypeDefList1{} = outputs
  ),
  do: %__MODULE__{doc: doc, name: name, inputs: inputs, outputs: outputs}

  @impl true
  def encode_xdr(%__MODULE__{doc: doc, name: name, inputs: inputs, outputs: outputs}) do
    [doc: doc, name: name, inputs: inputs, outputs: outputs]
    |> XDR.Struct.new()
    |> XDR.Struct.encode_xdr()
  end

  @impl true
  def encode_xdr!(%__MODULE__{doc: doc, name: name, inputs: inputs, outputs: outputs}) do
    [doc: doc, name: name, inputs: inputs, outputs: outputs]
    |> XDR.Struct.new()
    |> XDR.Struct.encode_xdr!()
  end

  @impl true
  def decode_xdr(bytes, struct \\ @struct_spec)

  def decode_xdr(bytes, struct) do
    case XDR.Struct.decode_xdr(bytes, struct) do
      {:ok, {%XDR.Struct{components: [doc: doc, name: name, inputs: inputs, outputs: outputs]}, rest}} ->
        {:ok, {new(doc, name, inputs, outputs), rest}}
      error -> error
    end
  end

  @impl true
  def decode_xdr!(bytes, struct \\ @struct_spec)

  def decode_xdr!(bytes, struct) do
    {%XDR.Struct{components: [doc: doc, name: name, inputs: inputs, outputs: outputs]}, rest} =
      XDR.Struct.decode_xdr!(bytes, struct)
    {new(doc, name, inputs, outputs), rest}
  end
end
