defmodule StellarBase.XDR.SCSpecTypeBytesN do
  @moduledoc """
  Automatically generated by xdrgen
  DO NOT EDIT or your changes may be overwritten

  Target implementation: elixir_xdr at https://hex.pm/packages/elixir_xdr

  Representation of Stellar `SCSpecTypeBytesN` type.
  """

  @behaviour XDR.Declaration

  alias StellarBase.XDR.{
    Uint32
  }

  @struct_spec XDR.Struct.new(
    n: Uint32
  )

  @type n_type :: Uint32.t()

  @type t :: %__MODULE__{n: n_type()}

  defstruct [:n]

  @spec new(n :: n_type()) :: t()
  def new(
    %Uint32{} = n
  ),
  do: %__MODULE__{n: n}

  @impl true
  def encode_xdr(%__MODULE__{n: n}) do
    [n: n]
    |> XDR.Struct.new()
    |> XDR.Struct.encode_xdr()
  end

  @impl true
  def encode_xdr!(%__MODULE__{n: n}) do
    [n: n]
    |> XDR.Struct.new()
    |> XDR.Struct.encode_xdr!()
  end

  @impl true
  def decode_xdr(bytes, struct \\ @struct_spec)

  def decode_xdr(bytes, struct) do
    case XDR.Struct.decode_xdr(bytes, struct) do
      {:ok, {%XDR.Struct{components: [n: n]}, rest}} ->
        {:ok, {new(n), rest}}
      error -> error
    end
  end

  @impl true
  def decode_xdr!(bytes, struct \\ @struct_spec)

  def decode_xdr!(bytes, struct) do
    {%XDR.Struct{components: [n: n]}, rest} =
      XDR.Struct.decode_xdr!(bytes, struct)
    {new(n), rest}
  end
end
