defmodule StellarBase.XDR.TransactionMetaV3 do
  @moduledoc """
  Automatically generated by xdrgen
  DO NOT EDIT or your changes may be overwritten

  Target implementation: elixir_xdr at https://hex.pm/packages/elixir_xdr

  Representation of Stellar `TransactionMetaV3` type.
  """

  @behaviour XDR.Declaration

  alias StellarBase.XDR.{
    LedgerEntryChanges,
    OperationMetaList,
    OperationEventsList,
    TransactionResult,
    HashFixedList,
    OperationDiagnosticEventsList
  }

  @struct_spec XDR.Struct.new(
    tx_changes_before: LedgerEntryChanges,
    operations: OperationMetaList,
    tx_changes_after: LedgerEntryChanges,
    events: OperationEventsList,
    tx_result: TransactionResult,
    hashes: HashFixedList,
    diagnostic_events: OperationDiagnosticEventsList
  )

  @type type_tx_changes_before :: LedgerEntryChanges.t()
  @type type_operations :: OperationMetaList.t()
  @type type_tx_changes_after :: LedgerEntryChanges.t()
  @type type_events :: OperationEventsList.t()
  @type type_tx_result :: TransactionResult.t()
  @type type_hashes :: HashFixedList.t()
  @type type_diagnostic_events :: OperationDiagnosticEventsList.t()

  @type t :: %__MODULE__{tx_changes_before: type_tx_changes_before(), operations: type_operations(), tx_changes_after: type_tx_changes_after(), events: type_events(), tx_result: type_tx_result(), hashes: type_hashes(), diagnostic_events: type_diagnostic_events()}

  defstruct [:tx_changes_before, :operations, :tx_changes_after, :events, :tx_result, :hashes, :diagnostic_events]

  @spec new(tx_changes_before :: type_tx_changes_before(), operations :: type_operations(), tx_changes_after :: type_tx_changes_after(), events :: type_events(), tx_result :: type_tx_result(), hashes :: type_hashes(), diagnostic_events :: type_diagnostic_events()) :: t()
  def new(
    %LedgerEntryChanges{} = tx_changes_before,
    %OperationMetaList{} = operations,
    %LedgerEntryChanges{} = tx_changes_after,
    %OperationEventsList{} = events,
    %TransactionResult{} = tx_result,
    %HashFixedList{} = hashes,
    %OperationDiagnosticEventsList{} = diagnostic_events
  ),
  do: %__MODULE__{tx_changes_before: tx_changes_before, operations: operations, tx_changes_after: tx_changes_after, events: events, tx_result: tx_result, hashes: hashes, diagnostic_events: diagnostic_events}

  @impl true
  def encode_xdr(%__MODULE__{tx_changes_before: tx_changes_before, operations: operations, tx_changes_after: tx_changes_after, events: events, tx_result: tx_result, hashes: hashes, diagnostic_events: diagnostic_events}) do
    [tx_changes_before: tx_changes_before, operations: operations, tx_changes_after: tx_changes_after, events: events, tx_result: tx_result, hashes: hashes, diagnostic_events: diagnostic_events]
    |> XDR.Struct.new()
    |> XDR.Struct.encode_xdr()
  end

  @impl true
  def encode_xdr!(%__MODULE__{tx_changes_before: tx_changes_before, operations: operations, tx_changes_after: tx_changes_after, events: events, tx_result: tx_result, hashes: hashes, diagnostic_events: diagnostic_events}) do
    [tx_changes_before: tx_changes_before, operations: operations, tx_changes_after: tx_changes_after, events: events, tx_result: tx_result, hashes: hashes, diagnostic_events: diagnostic_events]
    |> XDR.Struct.new()
    |> XDR.Struct.encode_xdr!()
  end

  @impl true
  def decode_xdr(bytes, struct \\ @struct_spec)

  def decode_xdr(bytes, struct) do
    case XDR.Struct.decode_xdr(bytes, struct) do
      {:ok, {%XDR.Struct{components: [tx_changes_before: tx_changes_before, operations: operations, tx_changes_after: tx_changes_after, events: events, tx_result: tx_result, hashes: hashes, diagnostic_events: diagnostic_events]}, rest}} ->
        {:ok, {new(tx_changes_before, operations, tx_changes_after, events, tx_result, hashes, diagnostic_events), rest}}
      error -> error
    end
  end

  @impl true
  def decode_xdr!(bytes, struct \\ @struct_spec)

  def decode_xdr!(bytes, struct) do
    {%XDR.Struct{components: [tx_changes_before: tx_changes_before, operations: operations, tx_changes_after: tx_changes_after, events: events, tx_result: tx_result, hashes: hashes, diagnostic_events: diagnostic_events]}, rest} =
      XDR.Struct.decode_xdr!(bytes, struct)
    {new(tx_changes_before, operations, tx_changes_after, events, tx_result, hashes, diagnostic_events), rest}
  end
end
