defmodule StellarBase.XDR.TransactionSignaturePayload do
  @moduledoc """
  Automatically generated by xdrgen
  DO NOT EDIT or your changes may be overwritten

  Target implementation: elixir_xdr at https://hex.pm/packages/elixir_xdr

  Representation of Stellar `TransactionSignaturePayload` type.
  """

  @behaviour XDR.Declaration

  alias StellarBase.XDR.{
    Hash,
    TransactionSignaturePayloadTaggedTransaction
  }

  @struct_spec XDR.Struct.new(
                 network_id: Hash,
                 tagged_transaction: TransactionSignaturePayloadTaggedTransaction
               )

  @type network_id_type :: Hash.t()
  @type tagged_transaction_type :: TransactionSignaturePayloadTaggedTransaction.t()

  @type t :: %__MODULE__{
          network_id: network_id_type(),
          tagged_transaction: tagged_transaction_type()
        }

  defstruct [:network_id, :tagged_transaction]

  @spec new(network_id :: network_id_type(), tagged_transaction :: tagged_transaction_type()) ::
          t()
  def new(
        %Hash{} = network_id,
        %TransactionSignaturePayloadTaggedTransaction{} = tagged_transaction
      ),
      do: %__MODULE__{network_id: network_id, tagged_transaction: tagged_transaction}

  @impl true
  def encode_xdr(%__MODULE__{network_id: network_id, tagged_transaction: tagged_transaction}) do
    [network_id: network_id, tagged_transaction: tagged_transaction]
    |> XDR.Struct.new()
    |> XDR.Struct.encode_xdr()
  end

  @impl true
  def encode_xdr!(%__MODULE__{network_id: network_id, tagged_transaction: tagged_transaction}) do
    [network_id: network_id, tagged_transaction: tagged_transaction]
    |> XDR.Struct.new()
    |> XDR.Struct.encode_xdr!()
  end

  @impl true
  def decode_xdr(bytes, struct \\ @struct_spec)

  def decode_xdr(bytes, struct) do
    case XDR.Struct.decode_xdr(bytes, struct) do
      {:ok,
       {%XDR.Struct{components: [network_id: network_id, tagged_transaction: tagged_transaction]},
        rest}} ->
        {:ok, {new(network_id, tagged_transaction), rest}}

      error ->
        error
    end
  end

  @impl true
  def decode_xdr!(bytes, struct \\ @struct_spec)

  def decode_xdr!(bytes, struct) do
    {%XDR.Struct{components: [network_id: network_id, tagged_transaction: tagged_transaction]},
     rest} = XDR.Struct.decode_xdr!(bytes, struct)

    {new(network_id, tagged_transaction), rest}
  end
end
