defmodule StellarBase.XDR.TransactionSet do
  @moduledoc """
  Automatically generated by xdrgen
  DO NOT EDIT or your changes may be overwritten

  Target implementation: elixir_xdr at https://hex.pm/packages/elixir_xdr

  Representation of Stellar `TransactionSet` type.
  """

  @behaviour XDR.Declaration

  alias StellarBase.XDR.{
    Hash,
    TransactionEnvelopeList
  }

  @struct_spec XDR.Struct.new(
    previous_ledger_hash: Hash,
    txs: TransactionEnvelopeList
  )

  @type type_previous_ledger_hash :: Hash.t()
  @type type_txs :: TransactionEnvelopeList.t()

  @type t :: %__MODULE__{previous_ledger_hash: type_previous_ledger_hash(), txs: type_txs()}

  defstruct [:previous_ledger_hash, :txs]

  @spec new(previous_ledger_hash :: type_previous_ledger_hash(), txs :: type_txs()) :: t()
  def new(
    %Hash{} = previous_ledger_hash,
    %TransactionEnvelopeList{} = txs
  ),
  do: %__MODULE__{previous_ledger_hash: previous_ledger_hash, txs: txs}

  @impl true
  def encode_xdr(%__MODULE__{previous_ledger_hash: previous_ledger_hash, txs: txs}) do
    [previous_ledger_hash: previous_ledger_hash, txs: txs]
    |> XDR.Struct.new()
    |> XDR.Struct.encode_xdr()
  end

  @impl true
  def encode_xdr!(%__MODULE__{previous_ledger_hash: previous_ledger_hash, txs: txs}) do
    [previous_ledger_hash: previous_ledger_hash, txs: txs]
    |> XDR.Struct.new()
    |> XDR.Struct.encode_xdr!()
  end

  @impl true
  def decode_xdr(bytes, struct \\ @struct_spec)

  def decode_xdr(bytes, struct) do
    case XDR.Struct.decode_xdr(bytes, struct) do
      {:ok, {%XDR.Struct{components: [previous_ledger_hash: previous_ledger_hash, txs: txs]}, rest}} ->
        {:ok, {new(previous_ledger_hash, txs), rest}}
      error -> error
    end
  end

  @impl true
  def decode_xdr!(bytes, struct \\ @struct_spec)

  def decode_xdr!(bytes, struct) do
    {%XDR.Struct{components: [previous_ledger_hash: previous_ledger_hash, txs: txs]}, rest} =
      XDR.Struct.decode_xdr!(bytes, struct)
    {new(previous_ledger_hash, txs), rest}
  end
end
