defmodule StellarBase.XDR.OperationMetaV2 do
  @moduledoc """
  Automatically generated by xdrgen
  DO NOT EDIT or your changes may be overwritten

  Target implementation: elixir_xdr at https://hex.pm/packages/elixir_xdr

  Representation of Stellar `OperationMetaV2` type.
  """

  @behaviour XDR.Declaration

  alias StellarBase.XDR.{
    ExtensionPoint,
    LedgerEntryChanges,
    ContractEventList
  }

  @struct_spec XDR.Struct.new(
                 ext: ExtensionPoint,
                 changes: LedgerEntryChanges,
                 events: ContractEventList
               )

  @type ext_type :: ExtensionPoint.t()
  @type changes_type :: LedgerEntryChanges.t()
  @type events_type :: ContractEventList.t()

  @type t :: %__MODULE__{ext: ext_type(), changes: changes_type(), events: events_type()}

  defstruct [:ext, :changes, :events]

  @spec new(ext :: ext_type(), changes :: changes_type(), events :: events_type()) :: t()
  def new(
        %ExtensionPoint{} = ext,
        %LedgerEntryChanges{} = changes,
        %ContractEventList{} = events
      ),
      do: %__MODULE__{ext: ext, changes: changes, events: events}

  @impl true
  def encode_xdr(%__MODULE__{ext: ext, changes: changes, events: events}) do
    [ext: ext, changes: changes, events: events]
    |> XDR.Struct.new()
    |> XDR.Struct.encode_xdr()
  end

  @impl true
  def encode_xdr!(%__MODULE__{ext: ext, changes: changes, events: events}) do
    [ext: ext, changes: changes, events: events]
    |> XDR.Struct.new()
    |> XDR.Struct.encode_xdr!()
  end

  @impl true
  def decode_xdr(bytes, struct \\ @struct_spec)

  def decode_xdr(bytes, struct) do
    case XDR.Struct.decode_xdr(bytes, struct) do
      {:ok, {%XDR.Struct{components: [ext: ext, changes: changes, events: events]}, rest}} ->
        {:ok, {new(ext, changes, events), rest}}

      error ->
        error
    end
  end

  @impl true
  def decode_xdr!(bytes, struct \\ @struct_spec)

  def decode_xdr!(bytes, struct) do
    {%XDR.Struct{components: [ext: ext, changes: changes, events: events]}, rest} =
      XDR.Struct.decode_xdr!(bytes, struct)

    {new(ext, changes, events), rest}
  end
end
