defmodule StellarBase.XDR.SorobanTransactionMetaV2 do
  @moduledoc """
  Automatically generated by xdrgen
  DO NOT EDIT or your changes may be overwritten

  Target implementation: elixir_xdr at https://hex.pm/packages/elixir_xdr

  Representation of Stellar `SorobanTransactionMetaV2` type.
  """

  @behaviour XDR.Declaration

  alias StellarBase.XDR.{
    SorobanTransactionMetaExt,
    OptionalSCVal
  }

  @struct_spec XDR.Struct.new(
                 ext: SorobanTransactionMetaExt,
                 return_value: OptionalSCVal
               )

  @type ext_type :: SorobanTransactionMetaExt.t()
  @type return_value_type :: OptionalSCVal.t()

  @type t :: %__MODULE__{ext: ext_type(), return_value: return_value_type()}

  defstruct [:ext, :return_value]

  @spec new(ext :: ext_type(), return_value :: return_value_type()) :: t()
  def new(
        %SorobanTransactionMetaExt{} = ext,
        %OptionalSCVal{} = return_value
      ),
      do: %__MODULE__{ext: ext, return_value: return_value}

  @impl true
  def encode_xdr(%__MODULE__{ext: ext, return_value: return_value}) do
    [ext: ext, return_value: return_value]
    |> XDR.Struct.new()
    |> XDR.Struct.encode_xdr()
  end

  @impl true
  def encode_xdr!(%__MODULE__{ext: ext, return_value: return_value}) do
    [ext: ext, return_value: return_value]
    |> XDR.Struct.new()
    |> XDR.Struct.encode_xdr!()
  end

  @impl true
  def decode_xdr(bytes, struct \\ @struct_spec)

  def decode_xdr(bytes, struct) do
    case XDR.Struct.decode_xdr(bytes, struct) do
      {:ok, {%XDR.Struct{components: [ext: ext, return_value: return_value]}, rest}} ->
        {:ok, {new(ext, return_value), rest}}

      error ->
        error
    end
  end

  @impl true
  def decode_xdr!(bytes, struct \\ @struct_spec)

  def decode_xdr!(bytes, struct) do
    {%XDR.Struct{components: [ext: ext, return_value: return_value]}, rest} =
      XDR.Struct.decode_xdr!(bytes, struct)

    {new(ext, return_value), rest}
  end
end
