defmodule StellarBase.XDR.ContractCostType do
  @moduledoc """
  Automatically generated by xdrgen
  DO NOT EDIT or your changes may be overwritten

  Target implementation: elixir_xdr at https://hex.pm/packages/elixir_xdr

  Representation of Stellar `ContractCostType` type.
  """

  @behaviour XDR.Declaration

  @declarations [
    WasmInsnExec: 0,
    MemAlloc: 1,
    MemCpy: 2,
    MemCmp: 3,
    DispatchHostFunction: 4,
    VisitObject: 5,
    ValSer: 6,
    ValDeser: 7,
    ComputeSha256Hash: 8,
    ComputeEd25519PubKey: 9,
    VerifyEd25519Sig: 10,
    VmInstantiation: 11,
    VmCachedInstantiation: 12,
    InvokeVmFunction: 13,
    ComputeKeccak256Hash: 14,
    DecodeEcdsaCurve256Sig: 15,
    RecoverEcdsaSecp256k1Key: 16,
    Int256AddSub: 17,
    Int256Mul: 18,
    Int256Div: 19,
    Int256Pow: 20,
    Int256Shift: 21,
    ChaCha20DrawBytes: 22,
    ParseWasmInstructions: 23,
    ParseWasmFunctions: 24,
    ParseWasmGlobals: 25,
    ParseWasmTableEntries: 26,
    ParseWasmTypes: 27,
    ParseWasmDataSegments: 28,
    ParseWasmElemSegments: 29,
    ParseWasmImports: 30,
    ParseWasmExports: 31,
    ParseWasmDataSegmentBytes: 32,
    InstantiateWasmInstructions: 33,
    InstantiateWasmFunctions: 34,
    InstantiateWasmGlobals: 35,
    InstantiateWasmTableEntries: 36,
    InstantiateWasmTypes: 37,
    InstantiateWasmDataSegments: 38,
    InstantiateWasmElemSegments: 39,
    InstantiateWasmImports: 40,
    InstantiateWasmExports: 41,
    InstantiateWasmDataSegmentBytes: 42,
    Sec1DecodePointUncompressed: 43,
    VerifyEcdsaSecp256r1Sig: 44,
    Bls12381EncodeFp: 45,
    Bls12381DecodeFp: 46,
    Bls12381G1CheckPointOnCurve: 47,
    Bls12381G1CheckPointInSubgroup: 48,
    Bls12381G2CheckPointOnCurve: 49,
    Bls12381G2CheckPointInSubgroup: 50,
    Bls12381G1ProjectiveToAffine: 51,
    Bls12381G2ProjectiveToAffine: 52,
    Bls12381G1Add: 53,
    Bls12381G1Mul: 54,
    Bls12381G1Msm: 55,
    Bls12381MapFpToG1: 56,
    Bls12381HashToG1: 57,
    Bls12381G2Add: 58,
    Bls12381G2Mul: 59,
    Bls12381G2Msm: 60,
    Bls12381MapFp2ToG2: 61,
    Bls12381HashToG2: 62,
    Bls12381Pairing: 63,
    Bls12381FrFromU256: 64,
    Bls12381FrToU256: 65,
    Bls12381FrAddSub: 66,
    Bls12381FrMul: 67,
    Bls12381FrPow: 68,
    Bls12381FrInv: 69,
    Bn254EncodeFp: 70,
    Bn254DecodeFp: 71,
    Bn254G1CheckPointOnCurve: 72,
    Bn254G2CheckPointOnCurve: 73,
    Bn254G2CheckPointInSubgroup: 74,
    Bn254G1ProjectiveToAffine: 75,
    Bn254G1Add: 76,
    Bn254G1Mul: 77,
    Bn254Pairing: 78,
    Bn254FrFromU256: 79,
    Bn254FrToU256: 80,
    Bn254FrAddSub: 81,
    Bn254FrMul: 82,
    Bn254FrPow: 83,
    Bn254FrInv: 84,
    Bn254G1Msm: 85
  ]

  @enum_spec %XDR.Enum{declarations: @declarations, identifier: nil}

  @type t :: %__MODULE__{identifier: atom()}

  defstruct [:identifier]

  @spec new(type :: atom()) :: t()
  def new(type \\ :WasmInsnExec), do: %__MODULE__{identifier: type}

  @impl true
  def encode_xdr(%__MODULE__{identifier: type}) do
    @declarations
    |> XDR.Enum.new(type)
    |> XDR.Enum.encode_xdr()
  end

  @impl true
  def encode_xdr!(%__MODULE__{identifier: type}) do
    @declarations
    |> XDR.Enum.new(type)
    |> XDR.Enum.encode_xdr!()
  end

  @impl true
  def decode_xdr(bytes, spec \\ @enum_spec)

  def decode_xdr(bytes, spec) do
    case XDR.Enum.decode_xdr(bytes, spec) do
      {:ok, {%XDR.Enum{identifier: type}, rest}} -> {:ok, {new(type), rest}}
      error -> error
    end
  end

  @impl true
  def decode_xdr!(bytes, spec \\ @enum_spec)

  def decode_xdr!(bytes, spec) do
    {%XDR.Enum{identifier: type}, rest} = XDR.Enum.decode_xdr!(bytes, spec)
    {new(type), rest}
  end
end
